version: 2
jobs:
    build:
        docker:
            - image: golang:1.12.6-alpine3.9
        steps:
            - run:
                name: Install packages
                command: apk add bash make git

            - checkout

            - run:
                name: Build binary
                command: make build

            - store_artifacts:
                path: ./terraform-provider-herokudata

    release:
        docker:
            - image: circleci/golang:1.15
        steps:
            - checkout
            - run: curl -sL https://git.io/goreleaser | bash

workflows:
    version: 2
    build:
        jobs:
            - build

            - release:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v\d+\.\d+$/
